development:
  adapter: async

test:
  adapter: test
  firebase_url    = 'https://fir-awesome-625cd.firebaseio.com/
   firebase_secret = '91N3KIyRNSo0uZXXgBciIvEPvnEUNjPzNN6qomKv'
   firebase = Firebase::Client.new(firebase_url, firebase_secret)

   response = firebase.push("todos", { :name => 'Pick the milk',        :priority => 1 })

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: traveltongue_backend_production
